services:
  db:
    image: mariadb:lts
    environment:
      MARIADB_USER: DrWho
      MARIADB_PASSWORD: SonicScrewdriver
      MARIADB_DATABASE: dicom
      MARIADB_RANDOM_ROOT_PASSWORD: true
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 3
      
  backend:
    build: dicom-backend
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: mysql://DrWho:SonicScrewdriver@db/dicom
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      start_period: 5s
      interval: 2s
      timeout: 2s
      retries: 10
  frontend:
    build: dicom-frontend
    ports:
      - 5173:5173
    depends_on:
      - backend